### ISSUE TITLE
Consider using peerDependencies

### ISSUE THREAD

**Issue by diegonc** [js-accounts/react#33]
If you follow the installation procedure stated in the README, there will be multiple versions of `@accounts/common` installed resulting in the following error when loading the page:

```
Uncaught (in promise) Error: no tokens provided
    at AccountsError.ExtendableBuiltin (http://192.168.56.101:3000/bundle.js:78029:29)
    at new AccountsError (http://192.168.56.101:3000/bundle.js:78059:117)
    at AccountsClient._callee7$ (http://192.168.56.101:3000/bundle.js:60416:24)
    at tryCatch (http://192.168.56.101:3000/bundle.js:17026:41)
    at Generator.invoke [as _invoke] (http://192.168.56.101:3000/bundle.js:17261:23)
    at Generator.prototype.(anonymous function) [as next] (http://192.168.56.101:3000/bundle.js:17078:22)
    at step (http://192.168.56.101:3000/bundle.js:60100:192)
    at http://192.168.56.101:3000/bundle.js:60100:362
```

You can reproduce it by starting a project from scratch, which as of today, leads to the following packages being installed:

```
yarn list v0.21.3
├─ @accounts/client@0.0.8
│  ├─ @accounts/common@^0.0.7
│  ├─ @accounts/common@0.0.7
│  │  └─ lodash@^4.16.4
│  ├─ immutable@^3.8.1
│  ├─ jwt-decode@^2.1.0
│  ├─ lodash@^4.16.4
│  ├─ redux-immutable@^3.0.8
│  └─ redux@^3.6.0
├─ @accounts/common@0.0.3
│  ├─ apollo-errors@^1.2.1
│  └─ lodash@^4.16.4
├─ @accounts/react-material-ui@0.0.4
│  ├─ @accounts/client@0.0.3
│  ├─ @accounts/client@0.0.3
```

Also, in js-accounts/examples you can remove client package from package.json and do
```
yarn add @accounts/client
```
now when you run the example the cited exception should appear.

This error is produced by the multiple versions of `@accounts/common`. By switching  to using peer dependencies the user of react and react-material-ui can upgrade other components of js-accounts independently as long as versions are compatible.

Does this make sense?

**Comment by TimMikeladze** [comment]
Yes it does. Do you mind sending PR?

**Comment by TimMikeladze** [comment]
Actually, no need for the PR, I'll handle this in mine.

**Comment by diegonc** [comment]
I don't know if GitHub notifies edits, so **ping** 😛

Just found out that only one version of `@accounts/client` must be in existence, commons is not to blame here. I updated the issue body and title.

**Comment by TimMikeladze** [comment]
Github edits don't notify. I wish they did (as well as reactions). 

Thanks.

**Comment by TimMikeladze** [comment]
Material ui should also be marked as a peer dependency.

**Comment by diegonc** [comment]
I'm not so sure about that one.
It's more like a one-of kind of dependency; you can have material, but also bootstrap, unstyled or whatever UI framework people implements.

**Comment by TimMikeladze** [comment]
Here is my reasoning: If the consuming code is using the `@accounts/react-material-ui` package then they already have the `material-ui` in their `package.json.` It should be also added as a dev dependency here so the storybook would work too.

**Comment by diegonc** [comment]
Oop, sorry, I thought you were referring to react-material-ui. Now it's crystal clear 😄
